### ISSUE TITLE
weekgrafiek

### ISSUE THREAD

**Issue by zavin-med** [TsukiyomiSachiko/Zavin-Slideshow-2.0-Issue-Tracker#1]
de waarde(n) van de weekgrafiek zijn niet juist. Volgens onze berekening hebben wij in week 44 ca. 213 ton verwerkt, volgens de grafiek is dit slechts 185 ton.

**Comment by TsukiyomiSachiko** [comment]
Wat zijn volgens jullie berekeningen de juiste aanvoer en productiewaarden in week 26? Wij hebben week 44 namelijk niet in onze database staan, dus kunnen daarop niet controleren of de nieuwe berekening correct is

**Comment by zavin-med** [comment]
De aanvoer KW26 is 220 ton en de productie is 214 ton
