### ISSUE TITLE
Waarden bovenin het scherm

### ISSUE THREAD

**Issue by zavin-med** [TsukiyomiSachiko/Zavin-Slideshow-2.0-Issue-Tracker#2]
Waarden bovenin het scherm (actuele productie en aanvoer) blijven op 0 staan.

**Comment by TsukiyomiSachiko** [comment]
Groeien de staven van de weekgrafiek wel?

**Comment by zavin-med** [comment]
Ja maar bij de afgelopen week. De nieuwe week is nog niet gestart.
